name: stocks_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  # Splash screen.
  flutter_native_splash: ^2.4.3
  # An SVG rendering and widget library, which allows painting.
  flutter_svg: ^2.0.16
  # For adapting screen and font size.
  flutter_screenutil: ^5.9.3
  # Dependency injection.
  get_it: ^8.0.3
  # Code generator (mainly used with cubit & retrofit).
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  # State management.
  flutter_bloc: ^8.1.6
  # Networking.
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5
  pretty_dio_logger: ^1.4.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^6.1.1
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.9.0
  # Scanning 2D barcodes and QRCodes via camera.
  barcode_scan2: ^4.3.3
  # reading and writing simple key-value pairs
  shared_preferences: ^2.3.4
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.2
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.2.0+3
  # Fully customizable OTP Entry TextField.
  flutter_otp_text_field: ^1.4.0+2
  # A secure authentication system for signing in with a Google account.
  google_sign_in: ^6.2.2
  #A highly customizable typeahead (autocomplete) text input field for Flutter
  flutter_typeahead: ^5.2.0
  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.1.2
  # API to request and check permissions.
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # To encourage good coding practices. The lint set provided by the package is
  flutter_lints: ^5.0.0
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.14
  # To change app's launcher icon.
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_thin.ttf
          weight: 100
        - asset: assets/fonts/inter_light.ttf
          weight: 300
        - asset: assets/fonts/inter_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_semibold.ttf
          weight: 600
        - asset: assets/fonts/inter_bold.ttf
          weight: 700